### ISSUE TITLE
linchpin rise/up error since upgrade to 1.0.0

### ISSUE THREAD

**Issue by danalanerh** [CentOS-PaaS-SIG/linchpin#267]
Running linchpin/cinch in a virtual environment. Did a linchpin upgrade with the command:

```
pip install -U linchpin==1.0.0
```

Following the upgrade run the command linchpin rise or linchpin up;

```
(venv) [vagrant@localhost CSS]$ linchpin up
Traceback (most recent call last):
  File "/home/vagrant/venv/bin/linchpin", line 11, in <module>
    sys.exit(runcli())
  File "/home/vagrant/venv/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/vagrant/venv/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/vagrant/venv/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/vagrant/venv/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/vagrant/venv/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/vagrant/venv/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/home/vagrant/venv/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/vagrant/venv/lib/python2.7/site-packages/linchpin/__init__.py", line 207, in up
    results = lpcli.lp_up(pf_w_path, targets)
  File "/home/vagrant/venv/lib/python2.7/site-packages/linchpin/api/__init__.py", line 321, in lp_up
    return self.run_playbook(pinfile, targets, playbook="up")
  File "/home/vagrant/venv/lib/python2.7/site-packages/linchpin/api/__init__.py", line 257, in run_playbook
    pf[target]["topology"]))
TypeError: string indices must be integers, not str
```

PinFile:
```
#The following example illustrates the linchpinfile , ie., lpf
#SYNTAX:
#component_name:
#    topology_name: <string>  # refers to the name topology file either in package or local topologies folder
#    inventory_layout: <string> # refers to name of the inventory layout in package or local layouts folder
#on linchpin rise ,  the folder structure is created as follows
# component_name:
# ---- outputs
# ---- keystore
# ---- inventory
topology_upstream: "https://github.com/CentOS-PaaS-SIG/linch-pin/"
layout_upstream: "https://github.com/CentOS-PaaS-SIG/linch-pin/"

cinch:
  topology: cinch.yml
  layout: cinch.yml

post_actions:
  print: "hello"
```

topology file:
```
---
topology_name: "cinch"
site: "ci-osp"
resource_groups:
  -
    resource_group_name: "CSS-testgroup"
    res_group_type: "openstack"
    res_defs:
      - res_name: "resource"
        flavor: "m1.small"
        res_type: "os_server"
        image: "rhel-7.2-server-x86_64-released"
        count: 1
        keypair: "<redacted>"
        networks:
          - "CSS"
        fip_pool: "<redacted>"
    assoc_creds: "os_creds"
```

**Comment by danalanerh** [comment]
Addiotnal debugging info: Updated the topology file and moved the credential file to what I believe is the proper location (Thanks David!)

Here is updated output:
https://pastebin.com/CSRbmuV9

**Comment by herlo** [comment]
See PR #268. I expect this to be merged today, at which point you can test and see if the fix works for you.

**Comment by herlo** [comment]
Fixed by #268, please verify and reopen this issue if needed.

**Comment by danalanerh** [comment]
Still failing in the same manner. Fails the checking topology against scheme_v3 and against schema_v4

TASK [common : check topology file against schema_v3] **************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": {"output": "ValidationError: {u'credentials': [{u'profile': u'e2e-openstack'}, {u'auth_type': u'file:os_creds.yml'}], u'res_group_type': u'openstack', u'res_defs': [{u'count': 1, u'res_type': u'os_server', u'image': u'rhel-7.2-server-x86_64-released', u'res_name': u'resource', u'keypair': u'css-central', u'fip_pool': u'10.8.172.0/22', u'flavor': u'm1.small', u'networks': [u'CSS']}], u'resource_group_name': u'CSS-testgroup'} is not valid under any of the given schemas", "path": "/home/vagrant/projects/CI/CSS-95/CSS/topologies/cinch.yml", "schema": "/home/vagrant/venv/lib/python2.7/site-packages/linchpin/defaults/schemas/schema_v3.json"}}
...ignoring

TASK [common : Set state for schema_v3 validation] *****************************
ok: [localhost]

TASK [common : assign schema_v3 output] ****************************************
skipping: [localhost]

TASK [common : check topology file against schema_v4] **************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": {"output": "ValidationError: {u'credentials': [{u'profile': u'e2e-openstack'}, {u'auth_type': u'file:os_creds.yml'}], u'res_group_type': u'openstack', u'res_defs': [{u'count': 1, u'res_type': u'os_server', u'image': u'rhel-7.2-server-x86_64-released', u'res_name': u'resource', u'keypair': u'css-central', u'fip_pool': u'10.8.172.0/22', u'flavor': u'm1.small', u'networks': [u'CSS']}], u'resource_group_name': u'CSS-testgroup'} is not valid under any of the given schemas", "path": "/home/vagrant/projects/CI/CSS-95/CSS/topologies/cinch.yml", "schema": "/home/vagrant/venv/lib/python2.7/site-packages/linchpin/defaults/schemas/schema_v4.json"}}
	to retry, use: --limit @/home/vagrant/venv/lib/python2.7/site-packages/linchpin/provision/site.retry

**Comment by herlo** [comment]
Alright, I got things working with a small set of adjustments. For schema_v4 (which is recommended), I suggest using something like this:

```
---
topology_name: cinch
resource_groups:
  -
    resource_group_name: CSS-testgroup
    resource_group_type: openstack
    resource_definitions:
      - name: rsrc1
        type: os_server
        flavor: m1.small
        image: rhel-7.2-server-x86_64-released
        count: 1
        keypair: ci-factory
```

What you might notice is that assoc_creds is not there. In v1.0.0, credentials default back to your system's credentials management according to the cloud provider used. In this case, that would be either ENV variables, or clouds.yaml (detail here: https://docs.openstack.org/developer/python-openstackclient/configuration.html).

Secondly, you'll notice that instead of res_grp and res_def, the words are spelled out. This was one of the required breaking changes for v1.0.0 to work properly. 

Lastly, I'll be filing a PR to fix the credentials bit right now as it currently requires a 'credentials' (formerly assoc_creds) option, which is no longer required. Once that PR is in place, it should work. 

If you don't want to wait for the PR to get merged, add 'credentials' at the same level you had 'assoc_creds' with some bogus value. Because of the way we changed the credential management, this value should get ignored and the credential explanation above will apply.

**Comment by herlo** [comment]
@danalanerh see above comment.

**Comment by herlo** [comment]
@danalanerh A couple other things for sanity, we've currently removed any upstream management, so taking out the following lines from the `PinFile` is going to help:
```
topology_upstream: "https://github.com/CentOS-PaaS-SIG/linch-pin/"
layout_upstream: "https://github.com/CentOS-PaaS-SIG/linch-pin/"
```
For Github, if you want to comment code, you can use three backticks (```) above and below the code you want to share. It makes reading the code cleaner. Github provides a nice 'Preview' tab with each comment to make it easy for you to see how things work. 

Thank you for your continued contributions here, it helps LinchPin become better as a whole!
