### ISSUE TITLE
After upgrade to linchpin 1.6.2, openstack provisioning giving me a res_def_add_vol error

### ISSUE THREAD

**Issue by danalanerh** [CentOS-PaaS-SIG/linchpin#712]
The following topology/layout files worked with v1.5.2, same host same venv. Also, with 1.6.2, my beaker provisioning works fine. It's just this openstack provision that's failing;
---------------------------------------------------------
Full output:

(linchpin) [root@pet-dlane-newjenkins-jmaster1 CSS_HCI]# linchpin -vvv -w ./ up
ctx.workspace: /var/lib/jenkins/workspace/demo-rhhi_pipeline-test/CSS_HCI
Processing target: os-server-addl-vols
rundb_id: 1
uhash: 7022fb
calling: preup
hook preup initiated
 [WARNING]: Unable to parse /var/lib/jenkins/workspace/demo-rhhi_pipeline-test/CSS_HCI/localhost as an inventory
source

 [WARNING]: No inventory was parsed, only implicit localhost is available

[DEPRECATION WARNING]: The use of 'include' for tasks has been deprecated. Use 'import_tasks' for static inclusions 
or 'include_tasks' for dynamic inclusions. This feature will be removed in a future release. Deprecation warnings can
 be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: include is kept for backwards compatibility but usage is discouraged. The module documentation
 details page may explain more about this rationale.. This feature will be removed in a future release. Deprecation 
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: Included file '/var/lib/jenkins/opt/linchpin/lib/python2.7/site-
packages/linchpin/provision/update_aws_cfn_outputs.yml' not found, however since this include is not explicitly 
marked as 'static: yes', we will try and include it dynamically later. In the future, this will be an error unless 
'static: no' is used on the include task. If you do not want missing includes to be considered dynamic, use 'static: 
yes' on the include or set the global ansible.cfg options to make all includes static for tasks and/or handlers. This
 feature will be removed in version 2.7. Deprecation warnings can be disabled by setting deprecation_warnings=False 
in ansible.cfg.

PLAYBOOK: openstack.yml **********************************************************************************************

PLAY [schema check and Pre-Provisioning Activities on topology_file] *************************************************

TASK [Gathering Facts] ***********************************************************************************************
ok: [localhost]

TASK [common : assign async value] ***********************************************************************************
task path: /var/lib/jenkins/opt/linchpin/lib/python2.7/site-packages/linchpin/provision/roles/common/tasks/main.yml:2
ok: [localhost] => {
    "ansible_facts": {
        "async": false
    }, 
    "changed": false, 
    "failed": false
}

TASK [common : declare async_types array] ****************************************************************************
task path: /var/lib/jenkins/opt/linchpin/lib/python2.7/site-packages/linchpin/provision/roles/common/tasks/main.yml:7
skipping: [localhost] => {
    "changed": false, 
    "skip_reason": "Conditional result was False", 
    "skipped": true
}

TASK [common : output vars] ******************************************************************************************
task path: /var/lib/jenkins/opt/linchpin/lib/python2.7/site-packages/linchpin/provision/roles/common/tasks/main.yml:12
ok: [localhost] => {
    "ansible_facts": {
        "topology_outputs": {}
    }, 
    "changed": false, 
    "failed": false
}

PLAY [Provisioning openstack resources] ******************************************************************************

TASK [Gathering Facts] ***********************************************************************************************
ok: [localhost]

TASK [openstack : declaring output vars] *****************************************************************************
task path: /var/lib/jenkins/opt/linchpin/lib/python2.7/site-packages/linchpin/provision/roles/openstack/tasks/main.yml:7
ok: [localhost] => {
    "ansible_facts": {
        "topology_outputs_os_heat": [], 
        "topology_outputs_os_keypair": [], 
        "topology_outputs_os_object": [], 
        "topology_outputs_os_server": [], 
        "topology_outputs_os_sg": [], 
        "topology_outputs_os_volume": []
    }, 
    "changed": false, 
    "failed": false
}

TASK [openstack : Initiating Provision/Teardown of openstack resource group] *****************************************
task path: /var/lib/jenkins/opt/linchpin/lib/python2.7/site-packages/linchpin/provision/roles/openstack/tasks/main.yml:16
included: /var/lib/jenkins/opt/linchpin/lib/python2.7/site-packages/linchpin/provision/roles/openstack/tasks/provision_resource_group.yml for localhost

TASK [openstack : Unset the authvar from previous run] ***************************************************************
task path: /var/lib/jenkins/opt/linchpin/lib/python2.7/site-packages/linchpin/provision/roles/openstack/tasks/provision_resource_group.yml:2
ok: [localhost] => {
    "ansible_facts": {
        "auth_var": ""
    }, 
    "changed": false, 
    "failed": false
}

TASK [openstack : set default_cred_profile when res_grp[credentials] is undefined] ***********************************
task path: /var/lib/jenkins/opt/linchpin/lib/python2.7/site-packages/linchpin/provision/roles/openstack/tasks/provision_resource_group.yml:6
skipping: [localhost] => {
    "changed": false, 
    "skip_reason": "Conditional result was False", 
    "skipped": true
}

TASK [openstack : set default_cred_profile when res_grp[credentials] is undefined] ***********************************
task path: /var/lib/jenkins/opt/linchpin/lib/python2.7/site-packages/linchpin/provision/roles/openstack/tasks/provision_resource_group.yml:11
skipping: [localhost] => {
    "changed": false, 
    "skip_reason": "Conditional result was False", 
    "skipped": true
}

TASK [openstack : set cred_profile when res_grp[credentials] is defined] *********************************************
task path: /var/lib/jenkins/opt/linchpin/lib/python2.7/site-packages/linchpin/provision/roles/openstack/tasks/provision_resource_group.yml:16
ok: [localhost] => {
    "ansible_facts": {
        "cred_profile": "CSS"
    }, 
    "changed": false, 
    "failed": false
}

TASK [openstack : set default_cred_filename when res_grp[credentials] is defined] ************************************
task path: /var/lib/jenkins/opt/linchpin/lib/python2.7/site-packages/linchpin/provision/roles/openstack/tasks/provision_resource_group.yml:21
ok: [localhost] => {
    "ansible_facts": {
        "cred_filename": "clouds.yaml"
    }, 
    "changed": false, 
    "failed": false
}

TASK [openstack : Get creds from auth driver] ************************************************************************
task path: /var/lib/jenkins/opt/linchpin/lib/python2.7/site-packages/linchpin/provision/roles/openstack/tasks/provision_resource_group.yml:26
fatal: [localhost]: FAILED! => {
    "censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", 
    "changed": false, 
    "failed": true
}
...ignoring

TASK [openstack : set auth_var] **************************************************************************************
task path: /var/lib/jenkins/opt/linchpin/lib/python2.7/site-packages/linchpin/provision/roles/openstack/tasks/provision_resource_group.yml:36
skipping: [localhost] => {
    "censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", 
    "changed": false, 
    "skipped": true
}

TASK [openstack : provisioning resource definitions of current group] ************************************************
task path: /var/lib/jenkins/opt/linchpin/lib/python2.7/site-packages/linchpin/provision/roles/openstack/tasks/provision_resource_group.yml:43
included: /var/lib/jenkins/opt/linchpin/lib/python2.7/site-packages/linchpin/provision/roles/openstack/tasks/provision_res_defs.yml for localhost

TASK [openstack : Set os_res_type value] *****************************************************************************
task path: /var/lib/jenkins/opt/linchpin/lib/python2.7/site-packages/linchpin/provision/roles/openstack/tasks/provision_res_defs.yml:2
skipping: [localhost] => {
    "changed": false, 
    "skip_reason": "Conditional result was False", 
    "skipped": true
}

TASK [openstack : Add resource type to async_types] ******************************************************************
task path: /var/lib/jenkins/opt/linchpin/lib/python2.7/site-packages/linchpin/provision/roles/openstack/tasks/provision_res_defs.yml:7
skipping: [localhost] => {
    "changed": false, 
    "skip_reason": "Conditional result was False", 
    "skipped": true
}

TASK [openstack : Get the resource name] *****************************************************************************
task path: /var/lib/jenkins/opt/linchpin/lib/python2.7/site-packages/linchpin/provision/roles/openstack/tasks/provision_res_defs.yml:12
ok: [localhost] => {
    "ansible_facts": {
        "os_resource_name": "database"
    }, 
    "changed": false, 
    "failed": false
}

TASK [openstack : Create name using uhash value] *********************************************************************
task path: /var/lib/jenkins/opt/linchpin/lib/python2.7/site-packages/linchpin/provision/roles/openstack/tasks/provision_res_defs.yml:16
skipping: [localhost] => {
    "changed": false, 
    "skip_reason": "Conditional result was False", 
    "skipped": true
}

TASK [openstack : provision/teardown resources }}] *******************************************************************
task path: /var/lib/jenkins/opt/linchpin/lib/python2.7/site-packages/linchpin/provision/roles/openstack/tasks/provision_res_defs.yml:21
skipping: [localhost] => {
    "changed": false, 
    "skip_reason": "Conditional result was False", 
    "skipped": true
}

TASK [openstack : provision/teardown resources }}] *******************************************************************
task path: /var/lib/jenkins/opt/linchpin/lib/python2.7/site-packages/linchpin/provision/roles/openstack/tasks/provision_res_defs.yml:25
included: /var/lib/jenkins/opt/linchpin/lib/python2.7/site-packages/linchpin/provision/roles/openstack/tasks/provision_os_server.yml for localhost

TASK [openstack : set_fact for res_def] ******************************************************************************
task path: /var/lib/jenkins/opt/linchpin/lib/python2.7/site-packages/linchpin/provision/roles/openstack/tasks/provision_os_server.yml:1
ok: [localhost] => {
    "ansible_facts": {
        "res_def_add_vol": [], 
        "res_def_names": []
    }, 
    "changed": false, 
    "failed": false
}

TASK [openstack : set_fact instance filters] *************************************************************************
task path: /var/lib/jenkins/opt/linchpin/lib/python2.7/site-packages/linchpin/provision/roles/openstack/tasks/provision_os_server.yml:6
ok: [localhost] => {
    "ansible_facts": {
        "res_def_prov": [
            {
                "name": "database1"
            }
        ]
    }, 
    "changed": false, 
    "failed": false
}

TASK [openstack : set_fact when addtional volumes] *******************************************************************
task path: /var/lib/jenkins/opt/linchpin/lib/python2.7/site-packages/linchpin/provision/roles/openstack/tasks/provision_os_server.yml:10
skipping: [localhost] => {
    "changed": false, 
    "skip_reason": "Conditional result was False", 
    "skipped": true
}

TASK [openstack : Provision additional volumes] **********************************************************************
task path: /var/lib/jenkins/opt/linchpin/lib/python2.7/site-packages/linchpin/provision/roles/openstack/tasks/provision_os_server.yml:15
fatal: [localhost]: FAILED! => {
    "failed": true, 
    "msg": "Unexpected failure in finding the lookup named '{{ res_def_add_vol }}' in the available lookup plugins"
}
	to retry, use: --limit @/var/lib/jenkins/opt/linchpin/lib/python2.7/site-packages/linchpin/provision/openstack.retry

PLAY RECAP ***********************************************************************************************************
localhost                  : ok=15   changed=0    unreachable=0    failed=1   

hook postinv initiated
Error: 'outputs'

Topology file;
---
topology_name: "css-jslave"
site: CSS
resource_groups:
  -
    resource_group_name: "CSS-OSP"
    resource_group_type: "openstack"
    resource_definitions:
      - name: "jslave"
        role: os_server
        flavor: "m1.large"
        # type: "os_server"
        image: "rhel-7.4-server-x86_64-released"
        count: 1
        keypair: "css-central"
        networks:
          - "CSS"
    # The profiles are defined in clouds.yaml, in the credentials folder
    credentials:
      filename: clouds.yaml
      profile: "CSS"

Layout file;
---
inventory_layout:
  hosts:
    CSS-OSP:
      count: 1
      host_groups:
        - rhel7
        - certificate_authority
        - repositories
        - jenkins_slave

pip freeze
(linchpin) [root@pet-dlane-newjenkins-jmaster1 CSS_HCI]# pip freeze
ansible==2.4.6.0
apache-libcloud==2.3.0
appdirs==1.4.3
asn1crypto==0.24.0
Babel==0.9.6
backports.ssl-match-hostname==3.4.0.2
bcrypt==3.1.4
beaker-client==25.5
beaker-common==25.5
boto==2.49.0
camel==0.1.2
Cerberus==1.2
certifi==2018.8.24
cffi==1.11.5
chardet==3.0.4
cinch==1.2.0
click==6.7
cloud-init==0.7.6
configobj==4.7.2
cryptography==2.3.1
decorator==3.4.0
deprecation==2.0.5
dogpile.cache==0.6.7
enum34==1.1.6
ethtool==0.8
functools32==3.2.3.post2
futures==3.2.0
idna==2.7
iniparse==0.4
ipaddress==1.0.22
IPy==0.75
iso8601==0.1.12
javapackages==1.0.0
Jinja2==2.7.2
jmespath==0.9.3
jsonpatch==1.23
jsonpointer==1.9
jsonschema==2.6.0
keystoneauth1==3.11.0
linchpin==1.6.2
lxml==3.2.1
M2Crypto==0.21.1
Magic-file-extensions==0.2
MarkupSafe==0.11
munch==2.3.2
Naked==0.1.31
netifaces==0.10.7
openstacksdk==0.17.2
os-client-config==1.31.2
os-service-types==1.3.0
packaging==17.1
paramiko==2.4.2
pbr==4.2.0
pciutils==1.7.3
perf==0.1
plumbum==1.6.7
policycoreutils-default-encoding==0.1
prettytable==0.7.2
pyasn1==0.4.4
pycparser==2.19
pycurl==7.19.0
pygobject==3.14.0
pygpgme==0.3
pyliblzma==0.5.3
PyNaCl==1.2.1
pyOpenSSL==0.13.1
pyparsing==2.2.1
pyserial==2.6
python-dateutil==1.5
python-dmidecode==3.10.13
pyudev==0.15
pyxattr==0.5.1
PyYAML==3.13
requests==2.19.1
requestsexceptions==1.4.0
rhnlib==2.5.65
rhsm==1.17.9
seobject==0.1
sepolicy==1.1
shade==1.29.0
six==1.11.0
slip==0.4.0
slip.dbus==0.4.0
stevedore==1.29.0
subscription-manager==1.17.15
tinydb==3.11.1
urlgrabber==3.10
urllib3==1.23
virtualenv==15.1.0
yamlordereddictloader==0.4.0
yum-metadata-parser==1.1.4

(linchpin) [root@pet-dlane-newjenkins-jmaster1 CSS_HCI]# cat /etc/os-release 
NAME="Red Hat Enterprise Linux Server"
VERSION="7.3 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="7.3"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.3 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.3:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.3
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.3"

**Comment by samvarankashyap** [comment]
@danalanerh : I think i found the cause . 
Its jinja version
The version of jinja you are using is 2.7.2 , however , when i see the environment we are using has jinja 2.10
```
pip install jinja==2.10
```
should solve the issue.

**Comment by danalanerh** [comment]
I did that and still get the same failure;
New pip freeze output:

(linchpin) [root@pet-dlane-newjenkins-jmaster1 CSS_HCI]# pip freeze
ansible==2.4.6.0
apache-libcloud==2.3.0
appdirs==1.4.3
asn1crypto==0.24.0
Babel==0.9.6
backports.ssl-match-hostname==3.4.0.2
bcrypt==3.1.4
beaker-client==25.5
beaker-common==25.5
boto==2.49.0
camel==0.1.2
Cerberus==1.2
certifi==2018.8.24
cffi==1.11.5
chardet==3.0.4
Cheetah==2.4.4
cinch==1.2.0
click==6.7
cloud-init==0.7.6
configobj==4.7.2
cryptography==2.3.1
decorator==3.4.0
deprecation==2.0.5
dogpile.cache==0.6.7
enum34==1.1.6
ethtool==0.8
functools32==3.2.3.post2
futures==3.2.0
idna==2.7
iniparse==0.4
ipaddress==1.0.22
IPy==0.75
iso8601==0.1.12
javapackages==1.0.0
Jinja2==2.10
jmespath==0.9.3
jsonpatch==1.23
jsonpointer==1.9
jsonschema==2.6.0
keystoneauth1==3.11.0
linchpin==1.6.2
lxml==3.2.1
M2Crypto==0.21.1
Magic-file-extensions==0.2
Markdown==3.0.1
MarkupSafe==1.0
munch==2.3.2
Naked==0.1.31
netifaces==0.10.7
oauth==1.0.1
openstacksdk==0.17.2
os-client-config==1.31.2
os-service-types==1.3.0
packaging==17.1
paramiko==2.4.2
pbr==4.2.0
pciutils==1.7.3
perf==0.1
plumbum==1.6.7
policycoreutils-default-encoding==0.1
prettytable==0.7.2
pyasn1==0.4.4
pycparser==2.19
pycurl==7.19.0
pygobject==3.14.0
pygpgme==0.3
pyliblzma==0.5.3
PyNaCl==1.2.1
pyOpenSSL==0.13.1
pyparsing==2.2.1
pyserial==2.6
python-dateutil==1.5
python-dmidecode==3.10.13
pyudev==0.15
pyxattr==0.5.1
PyYAML==3.13
requests==2.19.1
requestsexceptions==1.4.0
rhnlib==2.5.65
rhsm==1.17.9
seobject==0.1
sepolicy==1.1
shade==1.29.0
six==1.11.0
slip==0.4.0
slip.dbus==0.4.0
stevedore==1.29.0
subscription-manager==1.17.15
tinydb==3.11.1
urlgrabber==3.10
urllib3==1.23
virtualenv==15.1.0
yamlordereddictloader==0.4.0
yum-metadata-parser==1.1.4
(linchpin) [root@pet-dlane-newjenkins-jmaster1 CSS_HCI]#

**Comment by samvarankashyap** [comment]
@danalanerh could you try upgrading ansible to 2.6.4 
it might solve the issue with dependencies .

**Comment by samvarankashyap** [comment]
As discussed with @danalanerh
Upgrading ansible to 2.5 or above solves the problem with provisioning .

**Comment by danalanerh** [comment]
Yes, ansible 2.5 as well as 2.6.2 are both tested and proven to work. This can be closed.
